<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PowerPlanTray</AssemblyName>
    <RootNamespace>PowerPlanTray</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\bolt-white.svg" />
    <EmbeddedResource Include="assets\hp-white.svg" />
  </ItemGroup>
</Project>
